# Generated by Django 5.2.8 on 2025-12-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carcharacteristics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-price'], 'verbose_name': 'авто', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='carcategory',
            options={'verbose_name': 'категория авто', 'verbose_name_plural': 'Категории авто'},
        ),
        migrations.AlterModelOptions(
            name='carcharacteristics',
            options={'verbose_name': 'Характеристики авто', 'verbose_name_plural': 'Характеристики авто'},
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
